### ISSUE TITLE
change packets.js into packets.json

### ISSUE THREAD

**Issue by JasonChamness** [purduerov/X11-Core#2]
node is a dependency for scotty install sooooo it should be a part of the install!

- Ben Maxfield

**Comment by mattmolo** [comment]
Is it? Are you sure you don't want to keep scotty separate from the frontend development system?

**Comment by kingj5** [comment]
Agreed with Matt, Scotty is for the pi side. npm for surface. If we want to make a special script for surface installation of npm that sounds good but we don’t want to be bloating down the pi with npm and surface dependencies.

**Comment by AnotherOctopus** [comment]
ohhh, I think its because we are automatically generating the packet JSON for the rov to use by parsing the packet.js with node. Perhaps there is a better way

**Comment by mattmolo** [comment]
Well the `packet.js` file is really just JSON in a javascript file. The only real thing you would lose is comments (Because an actual json file doesn't allow comments sadly...).. But on the JS side it would be fine to just turn it into a json file. Then you wouldn't need to do conversion.

(Side idea: Write a custom DSL for the packet, something like protobuff)
